name: Deploy Go Application to Raspberry Pi

on:
  push:
    branches:
      - main  # Trigger deploy on push to the main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # This uses your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'  # Specify the Go version you need

      - name: Build Go application
        run: |
          go build -o budgee-api ./src

      - name: Stop budgee-api service
        run: |
          sudo systemctl stop budgee-api
        
      - name: Run database migrations
        run: migrate -path src/db/migrations -database "$PROD_DATABASE_URL" up
        env:
            PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

      - name: Copy Binary to user bin
        run: |
          sudo cp budgee-api /usr/local/bin/budgee-api

      - name: Start budgee-api service
        run: |
          sudo systemctl start budgee-api

      - name: Verify budgee-api service status
        run: |
          sudo systemctl status budgee-api --no-pager