name: Deploy Go Application to server

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
        env:
          GITHUB_ACTIONS_RUNNER_USE_IPV4: true

      - name: Build Go application
        run: |
          go build -o budgee-api ./src

      - name: Stop budgee-api service
        run: |
          sudo systemctl stop budgee-api
          sudo systemctl stop budgee-demo-api
        
      - name: Run database migrations
        run: | 
          migrate -path src/db/migrations -database "$PROD_DATABASE_URL" up
          migrate -path src/db/migrations -database "$DEMO_DATABASE_URL" up
        env:
            PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
            DEMO_DATABASE_URL: ${{ secrets.DEMO_DATABASE_URL }}

      - name: Copy Binary to user bin
        run: |
          sudo cp budgee-api /usr/local/bin/budgee-api
          sudo cp budgee-api /usr/local/bin/budgee-demo-api

      - name: Start budgee-api service
        run: |
          sudo systemctl start budgee-api
          sudo systemctl start budgee-demo-api

      - name: Verify budgee-api service status
        run: |
          sudo systemctl status budgee-api --no-pager
          sudo systemctl status budgee-demo-api --no-pager
